Computational Foundry Booking System/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using Computational_Foundry_Booking_System.Data;
using Computational_Foundry_Booking_System.Models.Data_Models.Accounts;
using Computational_Foundry_Booking_System.Models.Data_Models.Bookings;
using Computational_Foundry_Booking_System.Models.View_Models.Bookings;
using Computational_Foundry_Booking_System.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Computational_Foundry_Booking_System.Controllers {

    [Authorize]
    public class BookingsController : Controller {

        public const int DAYS_IN_WEEK = 7;
        private const DayOfWeek END_DAY = DayOfWeek.Friday;
        private const int WEEKEND_SPACING = (7 - (int) END_DAY)+1;
        private const int WEEK_DAYS_AVAILABLE = ((int) END_DAY - 1);
        private const int START_HOUR = 9;
        private const int END_HOUR = 17;
        private const int HOURS_SPACING = END_HOUR - START_HOUR;
        private const int MIN_SLOT_DURATION_HOURS = 1;

        private const int END_HOUR_START = START_HOUR
            + MIN_SLOT_DURATION_HOURS;

        private const int END_HOUR_END = END_HOUR + MIN_SLOT_DURATION_HOURS;

        private static readonly string[] DAYS_STR = { "Sun", "Mon", "Tue",
            "Wed", "Thu", "Fri", "Sat" };

        private static readonly HttpClientHandler clientHandler =
                new HttpClientHandler() {

            Credentials = new NetworkCredential(
                "cossharepoint\\administrator", "Admin!2019@vm")
        };

        private readonly HttpClient client = new HttpClient(clientHandler);

        private readonly AppUserRepository _appUserRepository;
        private readonly ResourcesRepository _resourcesRepository;

        public BookingsController(ApplicationDbContext dbContext,
                UserManager<AppUser> userManager,
                SignInManager<AppUser> signInManager) {

            _appUserRepository = new AppUserRepository(dbContext,
                userManager, signInManager);

            _resourcesRepository = new ResourcesRepository(dbContext,
                userManager, signInManager);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> WeeklyBookings() {
            DateTime weekStartDate = DateTime.Today;
            int dayOfThisWeek = (int) weekStartDate.DayOfWeek;
            TimeSpan daysFromSunday = new TimeSpan(dayOfThisWeek, 0, 0, 0);
            DateTime sundayDate = weekStartDate.Subtract(daysFromSunday);
            DateTime mondayDate = sundayDate.AddDays((int) DayOfWeek.Monday);

            List<Booking> weekBookings = await _resourcesRepository
                .GetWeekBookingsAsync(mondayDate);

            List<WeeklyBookingViewModel> weekBookingsViewModels;

            if(User.Identity.IsAuthenticated) {
                AppUser user = await _appUserRepository.GetUserAsync(User);

                weekBookingsViewModels = await AddWeeklyBookingsViewModels(
                    weekBookings, user);
            } else {
                weekBookingsViewModels = await AddWeeklyBookingsViewModels(
                    weekBookings);
            }

            WeeklyBookingsViewModel weeklyBookingsViewModel =
                    new WeeklyBookingsViewModel(mondayDate, END_DAY,
                    START_HOUR, END_HOUR);

            weeklyBookingsViewModel.AddBookings(weekBookingsViewModels);

            return View(weeklyBookingsViewModel);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> WeekBookings(string dateTime) {
            DateTime dateTimeParsed = DateTime.Parse(dateTime);

            int dayOfThisWeek = (int)dateTimeParsed.DayOfWeek;
            TimeSpan daysFromSunday = new TimeSpan(dayOfThisWeek, 0, 0, 0);
            DateTime sundayDate = dateTimeParsed.Subtract(daysFromSunday);
            DateTime mondayDate = sundayDate.AddDays((int) DayOfWeek.Monday);

            List<Booking> weekBookings = await _resourcesRepository
                .GetWeekBookingsAsync(mondayDate);

            List<WeeklyBookingViewModel> weekBookingsViewModels;

            if (User.Identity.IsAuthenticated) {
                AppUser user = await _appUserRepository.GetUserAsync(User);

                weekBookingsViewModels = await AddWeeklyBookingsViewModels(
                    weekBookings, user);
            } else {
                weekBookingsViewModels = await AddWeeklyBookingsViewModels(
                    weekBookings);
            }

            WeeklyBookingsViewModel weeklyBookingsViewModel =
                new WeeklyBookingsViewModel(mondayDate, END_DAY,
                START_HOUR, END_HOUR);

            weeklyBookingsViewModel.AddBookings(weekBookingsViewModels);

            return View("WeeklyBookings", weeklyBookingsViewModel);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> CurrentRoomBookings() {
            DateTime dateTime = DateTime.Now;
            DateTime dateTimeEnd = dateTime.AddHours(
                MIN_SLOT_DURATION_HOURS);

            RoomBookingsDateTimes roomBookingsDateTimes =
                SetupRoomBookingsDateTimes(dateTime);

            Room room = await _resourcesRepository.GetRoomAsync();

            List<Booking> roomBookings = await _resourcesRepository
                .GetRoomBookingsAsync(dateTime, dateTimeEnd);

            List<RoomBookingViewModel> roomBookingsViewModels;

            if (User.Identity.IsAuthenticated) {
                AppUser user = await _appUserRepository.GetUserAsync(User);

                roomBookingsViewModels = AddRoomBookingsViewModels(
                    roomBookings, user);
            } else {
                roomBookingsViewModels = AddRoomBookingsViewModels(
                    roomBookings);
            }

            RoomBookingsViewModel roomBookingsViewModel =
                new RoomBookingsViewModel(roomBookingsDateTimes, room);

            roomBookingsViewModel.AddBookings(roomBookingsViewModels);

            return View("RoomBookings", roomBookingsViewModel);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> RoomBookings(string dateTime) {
            DateTime dateTimeParsed = DateTime.Parse(dateTime);
            DateTime dateTimeEnd = dateTimeParsed.AddHours(
                MIN_SLOT_DURATION_HOURS);

            RoomBookingsDateTimes roomBookingsDateTimes =
                SetupRoomBookingsDateTimes(dateTimeParsed);

            Room room = await _resourcesRepository.GetRoomAsync();

            List<Booking> roomBookings = await _resourcesRepository
                .GetRoomBookingsAsync(dateTimeParsed, dateTimeEnd);

            List<RoomBookingViewModel> roomBookingsViewModels;

            if (User.Identity.IsAuthenticated) {
                AppUser user = await _appUserRepository.GetUserAsync(User);

                roomBookingsViewModels = AddRoomBookingsViewModels(
                    roomBookings, user);
            } else {
                roomBookingsViewModels = AddRoomBookingsViewModels(
                    roomBookings);
            }

            RoomBookingsViewModel roomBookingsViewModel =
                new RoomBookingsViewModel(roomBookingsDateTimes, room);

            roomBookingsViewModel.AddBookings(roomBookingsViewModels);

            return View(roomBookingsViewModel);
        }

        private RoomBookingsDateTimes SetupRoomBookingsDateTimes(
                DateTime selectedDateTime) {

            DayOfWeek dayOfThisWeek = selectedDateTime.DayOfWeek;
            int hour = selectedDateTime.Hour;

            if (hour < START_HOUR) {
                selectedDateTime = selectedDateTime.AddHours(
                    START_HOUR - hour);

            } else if (hour > END_HOUR) {
                selectedDateTime = selectedDateTime.AddHours(
                    END_HOUR - hour);
            }

            if (dayOfThisWeek < DayOfWeek.Monday) {
                selectedDateTime = selectedDateTime.AddDays(
                    DayOfWeek.Monday - dayOfThisWeek);

            } else if (dayOfThisWeek > END_DAY) {
                selectedDateTime = selectedDateTime.AddDays(
                    END_DAY - dayOfThisWeek);
            }

            dayOfThisWeek = selectedDateTime.DayOfWeek;
            hour = selectedDateTime.Hour;

            DateTime nextDay;
            DateTime previousDay;
            DateTime nextHour;
            DateTime previousHour;

            if (dayOfThisWeek == END_DAY) {
                nextDay = selectedDateTime.AddDays(WEEKEND_SPACING);
                previousDay = selectedDateTime.AddDays(-1);
            } else {
                nextDay = selectedDateTime.AddDays(1);

                if (dayOfThisWeek == DayOfWeek.Monday) {
                    previousDay = selectedDateTime.AddDays(-WEEKEND_SPACING);
                } else {
                    previousDay = selectedDateTime.AddDays(-1);
                }
            }

            if (hour == END_HOUR) {
                nextHour = selectedDateTime.AddHours(-HOURS_SPACING);
                previousHour = selectedDateTime.AddHours(-1);
            } else {
                nextHour = selectedDateTime.AddHours(1);

                if (hour == START_HOUR) {
                    previousHour = selectedDateTime.AddHours(HOURS_SPACING);
                } else {
                    previousHour = selectedDateTime.AddHours(-1);
                }
            }

            return new RoomBookingsDateTimes(selectedDateTime, nextDay,
                previousDay, nextHour, previousHour);
        }

        [HttpPost]
        [Authorize(Policy = Claims.CAN_BOOK)]

Computational Foundry Booking System/Views/Shared/_BookingFormPartial.cshtml
@using Computational_Foundry_Booking_System.Models.View_Models.Bookings
@model NewBookingViewModel

<div class="common-validation" asp-validation-summary="All"></div>
<form class="common-form" method="post" asp-controller="Bookings"
      asp-action="MakeBooking">
  <table class="common-table-form">
    <tr>
      <td></td>
      <td><h3 class="form-heading">Book</h3></td>
    </tr>
    @{ await Html.RenderPartialAsync("_ModelDisplayPartial"); }
    <tr>
      <td></td>
      <td><input type="submit" value="Book" class="form-btn" /></td>
    </tr>
  </table>
</form>

Computational Foundry Booking System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Computational Foundry</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/scripts/jquery-3.3.1.min.js"></script>
</head>
<body>
  <div id="out-div">
    <partial name="_NavBarPartial" />
    <div class="container">
      <partial name="_CookieConsentPartial" />
      <main role="main" class="pb-3">
        @RenderBody()
      </main>
    </div>

    <footer class="border-top footer text-muted">
      <div class="container">
        &copy; 2019 - Computational Foundry - <a asp-controller="Home" asp-action="Privacy">Privacy</a>
      </div>
    </footer>
  </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Computational Foundry Booking System/Views/Shared/_ModelDisplayPartial.cshtml
@using Microsoft.AspNetCore.Mvc.ModelBinding

@{
  IEnumerator<ModelExplorer> modelEnumerator = ViewData.ModelExplorer
    .Properties.GetEnumerator();
}

@foreach (ModelMetadata property in ViewData.ModelMetadata.Properties) {
  modelEnumerator.MoveNext();
  ModelExplorer modelExpl = modelEnumerator.Current;
  bool isArray = modelExpl.ModelType.IsArray;
  if (isArray) {
    object[] arr = modelExpl.Model as object[];
    int count = arr.Length;

    if (property.HideSurroundingHtml) {
      for (int i = 0; i < count; i++) {
        @Html.Editor(property.PropertyName + "[" + i + "]",
          property.DataTypeName, new { Value = arr[i], Hidden = true })
      }
    } else {
      for (int i = 0; i < count; i++) {
      <tr>
        <td></td>
        <td>
          <label class="common-label" id="login_label">@property.DisplayName</label>
          @Html.Editor(property.PropertyName + "[" + i + "]",
            property.DataTypeName, new { Value = arr[i], Hidden = false })
        </td>
      </tr>
      }
    }
  } else {
    if (property.HideSurroundingHtml) {
      @Html.Editor(property.PropertyName, new { Value = modelExpl.Model, Hidden = true })
    } else {
      <tr>
        <td></td>
        <td>
          <label class="common-label" id="login_label">@property.DisplayName</label>
          @Html.Editor(property.PropertyName, new { Value = modelExpl.Model, Hidden = false })
        </td>
      </tr>
    }
  }
}

Computational Foundry Booking System/Views/Shared/_NavBarPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Computational_Foundry_Booking_System.Models.Data_Models.Accounts
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

<header>
  <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
    <div class="container">
      <a class="navbar-brand" asp-controller="Home" asp-action="Index">Computational Foundry</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
        <ul class="navbar-nav">
          @if (SignInManager.IsSignedIn(User)) {
            <li class="nav-item">
              <a asp-controller="Account" asp-action="Manage">Account</a>
            </li>
            <li class="nav-item">
              <a asp-controller="Account" asp-action="Logout">Logout</a>
            </li>
          } else {
            <li class="nav-item">
              <a asp-controller="Account" asp-action="Register">Register</a>
            </li>
            <li class="nav-item">
              <a asp-controller="Account" asp-action="Login">Login</a>
            </li>
          }
        </ul>
        <ul class="navbar-nav flex-grow-1">
          <li class="nav-item">
            <a asp-controller="Home" asp-action="Privacy">
              Privacy
            </a>
            <a asp-controller="Bookings" asp-action="WeeklyBookings">
              Bookings
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>